### ISSUE TITLE
Update 2020 parameters

### ISSUE THREAD

**Issue by Eric-Sommer** [iza-institute-of-labor-economics/gettsim#124]
At the beginning of January, each and every parameter should be looked up and updated if necessary. 

Incomplete list of changes becoming effective 01-01-2020:
- [x] Starke-Familien-Gesetz, already implemented in #57 .
- [x] [FamEntlastG](https://www.buzer.de/3_Familienentlastungsgesetz.htm): Tax tariff and child tax allowance (#135 )
- [x] One or several social security contribution rates (#136 )
- [x] ALG2-Regelsätze (#139)

**Comment by mjbloemer** [comment]
Good to have a central list. Changes can be addressed in smaller PRs.

5. Wohngeld reform https://offenegesetze.de/veroeffentlichung/bgbl1/2019/44#page=5, https://www.faz.net/aktuell/wirtschaft/bundestag-verabschiedet-wohngelderhoehung-fuer-geringverdiener-16439571.html

@stmlitsche: Can you address point 4? The new ALG II parameters: https://offenegesetze.de/veroeffentlichung/bgbl1/2019/36#page=20

**Comment by mjbloemer** [comment]
6. New values Mindestunterhalt for 2020 and 2021: V. v. 12.09.2019 BGBl. I S. 1393 (see [offenegesetze.de](https://offenegesetze.de/veroeffentlichung/bgbl1/2019/34#page=9) and [buzer.de](https://www.buzer.de/gesetz/13566/a228484.htm)).

**Comment by Eric-Sommer** [comment]
7. Update old-age pension paramters.
